/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BadgeId = IDL.Nat;
export const Time = IDL.Int;
export const SkillBadge = IDL.Record({
  'id' : BadgeId,
  'verified' : IDL.Bool,
  'owner' : IDL.Principal,
  'skillName' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'level' : IDL.Opt(IDL.Text),
  'issuer' : IDL.Principal,
  'issueTimestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'organization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBadges' : IDL.Func([], [IDL.Vec(SkillBadge)], ['query']),
  'getBadgesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SkillBadge)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueBadge' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [BadgeId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyBadge' : IDL.Func([BadgeId], [IDL.Opt(SkillBadge)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BadgeId = IDL.Nat;
  const Time = IDL.Int;
  const SkillBadge = IDL.Record({
    'id' : BadgeId,
    'verified' : IDL.Bool,
    'owner' : IDL.Principal,
    'skillName' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'level' : IDL.Opt(IDL.Text),
    'issuer' : IDL.Principal,
    'issueTimestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'organization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBadges' : IDL.Func([], [IDL.Vec(SkillBadge)], ['query']),
    'getBadgesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SkillBadge)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueBadge' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [BadgeId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyBadge' : IDL.Func([BadgeId], [IDL.Opt(SkillBadge)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };